---
- name: Install AD-Domain-Services feature
  win_feature:
    name: AD-Domain-Services
    include_management_tools: "yes"
    include_sub_features:  "yes"
    state: present

- name: Create the domain
  win_domain:
    dns_domain_name: "{{ domain_name }}"
    domain_netbios_name: "{{ netbios_name }}"
    safe_mode_password: "{{ safe_mode_password }}"
